name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      tags:
        description: Tags to be run
        required: false
        default: ''
      env:
        description: Environment to be run
        required: false
        default: staging

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci
      - name: Cache Browser
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: |
          npx playwright install-deps
          npx playwright install chromium
      - name: Generate BDD
        run: npx bddgen
      - name: Run Playwright tests
        run: |
          # Run with tags if provided
          if [ "${{ github.event.inputs.tags }}" != "" ]; then
            npx playwright test --grep "${{ github.event.inputs.tags }}"
          else
            npx playwright test --reporter=html,line
          fi
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
